# Generated by Django 4.2.1 on 2024-03-25 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='location',
            field=models.CharField(default='base', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
            preserve_default=False,
        ),
    ]
